### ISSUE TITLE
Transfer PyPI ownership?

### ISSUE THREAD

**Issue by johnwmillr** [sebbekarlsson/spoonacular#1]
Hi Sebastian,

I have been working on a Python wrapper for the Spoonacular API and intend to maintain the project into the future. Here is the [GitHub repository](https://github.com/johnwmillr/SpoonacularAPI). I have already written methods and unit tests for nearly all of the Spoonacular API endpoints and have continuous integration going for the project on [Travis-CI](https://travis-ci.org/johnwmillr/SpoonacularAPI).

Would you be willing to transfer ownership of your package to me [on PyPI](https://pypi.org/project/spoonacular/)? Of course, I'd be happy for a collaborator if you're interested in helping develop this more fleshed out version of the Python wrapper.

Thank you,
John

**Comment by sebbekarlsson** [comment]
Hello John.

My wrapper does not really use their API, it is sort of scraping their
"API" used in their demo, so our implementations are sort of different.
I will give you the ownership of my package on PyPI though, it does not
really matter to me.

Do you have any idea how I would transfer the ownership to you? I am not
very experienced with PyPI.
Tell me how I do it and I will do it.

Thanks, Sebastian

2018-08-09 20:38 GMT+02:00 John <notifications@github.com>:

**Comment by johnwmillr** [comment]
Thank you for getting back to me, Sebastian.

I think our options are for you to either 1) add me as an owner to your project on PyPI or 2) delete the PyPI project, and I will start one with the same `spoonacular` name.

I am fine with either option, but in either case I will end up replacing all of the code in the project.

The steps are similar for both options:
  1.  Sign in to [PyPI](https://pypi.org/account/login/) and go to your [list of projects](https://pypi.org/manage/projects/)
  2.  Click the "Manage Project" button on the [`spoonacular`](https://pypi.org/project/spoonacular/) project.

To add me as a collaborator:

  3. Click on "Collaborators" on the left side
  4. Add me as a project owner using my PyPI username: `johnwmillr`

Or, to delete the project:

  3. Click on "Settings" on the left side
  4. Click on the "Delete Project" button

**Comment by sebbekarlsson** [comment]
Thank you John!

I have now added the username `johnwmillr` as a collaborator!
Do whatever you want with the source code, replace it with yours!

Have fun

**Comment by sebbekarlsson** [comment]
I did also update the REAMDE.md in my project to encourage people to use your wrapper instead.

**Comment by johnwmillr** [comment]
Thank you, Sebastian! I'll be sure to credit you in the README.

Did you add me as a collaborator or owner? I think you'll need to add me as an owner - I see that I've been added to the project, but I don't have any access to manage/edit the project.

Edit: Hmm, I see from the auto-generated email that you did add me as an owner. I'll try to figure out why I don't have manage access.

**Comment by sebbekarlsson** [comment]
Sorry, you were only a maintainer.

I have now set your role to `Owner`.

**Comment by johnwmillr** [comment]
Thank you for your help here, Sebastian! I’ve updated the package on PyPI now.

I’ll close the issue.

**Comment by sebbekarlsson** [comment]
No problem <3
